export interface Publication {
  id: string;
  title: string;
  authors: string[];
  year: string;
  venue: string;
  type: "journal" | "conference" | "workshop";
  indexing: "Scopus" | "Google Scholar";
  link?: string;
}

export const publications: Publication[] = [
  {
    id: "1",
    indexing: "Scopus",
    title: "Autonomous Healthcare Systems: Deep Learning-Based IoT Solutions for Continuous Monitoring and Adaptive Treatment",
    authors: ["Dr. G. B. Sambare", "Harsha Bhute", "et al."],
    year: "2024",
    venue: "Journal of Electrical Systems, Vol. 20-1s",
    type: "journal",
    link: "https://doi.org/10.52783/jes.780",
  },
  {
    id: "2",
    indexing: "Scopus",
    title: "Comparative Analysis of Human Pose Estimation Methods with Fall Detection and Smart Alarming System",
    authors: ["Dr. Rahul Patil", "Dr. Prashant Ahire", "Dr. G. B. Sambare", "et al."],
    year: "2024",
    venue: "Journal of Electrical Systems, Vol. 20-2",
    type: "journal",
    link: "https://doi.org/10.52783/jes.1996",
  },
  {
    id: "3",
    indexing: "Scopus",
    title: "Detecting Cyber-Attacks in the Industrial Internet of Things Using a Hybrid Deep Random Neural Network",
    authors: ["Dr. Mrunal K. Pathak", "Arti Bang", "Dr. G. B. Sambare", "et al."],
    year: "2024",
    venue: "Journal of Electrical Systems, Vol. 20-1s",
    type: "journal",
    link: "https://doi.org/10.52783/jes.762",
  },
  {
    id: "4",
    indexing: "Scopus",
    title: "Towards Enhanced Security: An Improved Approach to Phishing Email Detection",
    authors: ["Dr. G. B. Sambare", "Shailesh Galande", "Sharvari Kale", "et al."],
    year: "2024",
    venue: "Journal of Electrical Systems, Vol. 20-2",
    type: "journal",
    link: "https://doi.org/10.52783/jes.2054",
  },
  {
    id: "5",
    indexing: "Scopus",
    title: "AI-Driven Traffic Management Systems In Smart Cities: A Review",
    authors: ["Ravina D Chavan", "Dr. G. B. Sambare"],
    year: "2024",
    venue: "Educational Administration: Theory and Practice, Vol. 30(5)",
    type: "journal",
    link: "https://doi.org/10.53555/kuey.v30i5.2780",
  },
  {
    id: "6",
    indexing: "Scopus",
    title: "Translating Gestures: Utilizing CNN to Enhance ASL Communication and Understanding",
    authors: ["Dr. G. B. Sambare", "Shailesh Galande", "Purnesh Joshi", "et al."],
    year: "2024",
    venue: "Journal of Electrical Systems, Vol. 20 No. 6s",
    type: "journal",
    link: "https://doi.org/10.52783/jes.3281",
  },
  {
    id: "7",
    indexing: "Scopus",
    title: "Securing Cloud-Based IoT Architectures: A Multi-Protocol Approach",
    authors: ["Dr. H. B. Jadhav", "Dr. G. B. Sambare", "et al."],
    year: "2024",
    venue: "Computer Fraud and Security (Elsevier), Vol. 2024 Iss: 7",
    type: "journal",
    link: "https://doi.org/10.52710/cfs.33",
  },
  {
    id: "8",
    indexing: "Scopus",
    title: "Explainable Machine Learning Models for Real-Time Threat Detection in Cybersecurity",
    authors: ["Bhagyashree D Shendkar", "G B Sambare", "et al."],
    year: "2025",
    venue: "Panamerican Mathematical Journal, Vol 35 No. 1s",
    type: "journal",
    link: "https://doi.org/10.52783/pmj.v35.i1s.2313",
  },
  {
    id: "9",
    indexing: "Google Scholar",
    title: "Crowdfunding Using Blockchain for Startup Ventures",
    authors: ["S. S. Sambare", "Kalyani Khandait", "Kshitij Kolage", "Tanvi Nimbalkar", "Keyur Kolambe"],
    year: "2023",
    venue: "International Journal of Computer Applications, Vol. 185 – No. 10",
    type: "journal",
  },
  {
    id: "10",
    indexing: "Scopus",
    title: "Land Registry Using Blockchain",
    authors: ["Disha Shinde", "Snehal Padekar", "S. S. Sambare"],
    year: "2020",
    venue: "Journal of Critical Reviews (Web of Science), Vol 7, Issue 19",
    type: "journal",
  },
  {
    id: "11",
    indexing: "Scopus",
    title: "Blockchain-Based Secure Data Storage and Access Control System Using IPFS",
    authors: ["Shubham Desai", "Onkar Deshmukh", "Rahul Shelke", "S. S. Sambare"],
    year: "2020",
    venue: "Journal of Critical Reviews (Web of Science), Vol 7, Issue 19",
    type: "journal",
  },
  {
    id: "12",
    indexing: "Google Scholar",
    title: "Energy Efficient MIH-Based Independent and Heterogeneous Vertical Handover Algorithm",
    authors: ["S. S. Sambare", "Dr. M. U. Kharat", "Avinash U. Jadhav"],
    year: "2018",
    venue: "International Journal of Computer Applications, Vol. 182 – No. 21",
    type: "journal",
  },
  {
    id: "13",
    indexing: "Google Scholar",
    title: "Predicting Human Movement Based on Telecom Network Data",
    authors: ["S. S. Sambare", "Dr. M. U. Kharat"],
    year: "2017",
    venue: "International Journal of Computer Applications, Vol. 167 – No. 4",
    type: "journal",
  },
  {
    id: "14",
    indexing: "Google Scholar",
    title: "Algorithm to Analyze the Probability of False Initiation in Order to Provide Seamless Mobility",
    authors: ["S. S. Sambare", "Dr. M. U. Kharat"],
    year: "2017",
    venue: "International Journal of Computer Applications, Vol. 167 – No. 4",
    type: "journal",
  },
  {
    id: "15",
    indexing: "Google Scholar",
    title: "An Integrated WLAN and WiMAX with QoS-Based Vertical Handoff Scheme",
    authors: ["S. S. Sambare", "Madhuri R. Pawar"],
    year: "2013",
    venue: "IJCNWMC, Vol. 2, Issue 3",
    type: "journal",
  },
  {
    id: "16",
    indexing: "Scopus",
    title: "Gmail Phishing Detector Extension: A Machine Learning-Based Chrome Extension",
    authors: ["Dr. G. B. Sambare", "Gauri Pawar", "et al."],
    year: "2025",
    venue: "10th ICT4SD 2025, Springer, Goa, India",
    type: "conference",
  },
  {
    id: "17",
    indexing: "Scopus",
    title: "Stock Recommendations Leveraging AI/ML for Informed Long-Term Investment Decisions",
    authors: ["Dr. Govind Sambare", "Lalit Deore", "Harsh Itkar", "Onkar Jadhav", "Sarthak Joshi"],
    year: "2025",
    venue: "10th ICT4SD 2025, Springer, Goa, India",
    type: "conference",
  },
  {
    id: "18",
    indexing: "Scopus",
    title: "Survey of Interactive Document Query Systems Using RAG and LangChain",
    authors: ["Dr. G. B. Sambare", "Vedant Sonawane", "et al."],
    year: "2025",
    venue: "IEEE ICOCT 2025",
    type: "conference",
  },
  {
    id: "19",
    indexing: "Scopus",
    title: "Implementation of an Interactive Query System Using Nomic Text Embed and DeepSeek R1 1.5B",
    authors: ["Vedant Sonawane", "Dr. G. B. Sambare"],
    year: "2025",
    venue: "IEEE ICOCT 2025",
    type: "conference",
  },
  {
    id: "20",
    indexing: "Scopus",
    title: "Blockchain-Enhanced KYC: A Secure and Decentralized Framework for Identity Verification",
    authors: ["Dr. G. B. Sambare", "Sankarsha Shelke", "Sahil Wawdhane", "Harshad Wable", "Abhinav Thube"],
    year: "2025",
    venue: "10th ICT4SD 2025, Springer, Goa, India",
    type: "conference",
  },
  {
    id: "21",
    indexing: "Scopus",
    title: "Document Verification System and Validation Against QR Codes",
    authors: ["S.S. Sambare", "Utkarsh Pathak", "Venu Sonavane", "Mitali Gadiya", "Suyash Musale"],
    year: "2023",
    venue: "IEEE ICCUBEA",
    type: "conference",
  },
  {
    id: "22",
    indexing: "Scopus",
    title: "The Role of Blockchain for Sustainable Agri-Food Supply Chain Management",
    authors: ["S. S. Sambare", "Madhukar R Borphalkar", "Atharva Utekar", "Vaishnavi Salunkhe"],
    year: "2022",
    venue: "IEEE ICCUBEA",
    type: "conference",
  },
  {
    id: "23",
    indexing: "Scopus",
    title: "Automated Platform for Onboarding Employees",
    authors: ["S. S. Sambare", "Akriti Singh", "Chirag Kriplani", "Shweta Kale", "Tanuj Balkhande"],
    year: "2022",
    venue: "IEEE ICCUBEA",
    type: "conference",
  },
  {
    id: "24",
    indexing: "Scopus",
    title: "Land Registry Using Blockchain - A Survey of Existing Systems and Proposing a Feasible Solution",
    authors: ["Disha Shinde", "Snehal Padekar", "S. S. Sambare", "Abdul Wasay"],
    year: "2019",
    venue: "IEEE ICCUBEA",
    type: "conference",
  },
  {
    id: "25",
    indexing: "Scopus",
    title: "Blockchain-Based Secure Data Storage and Access Control System Using Cloud",
    authors: ["Shubham Desai", "Onkar Deshmukh", "Rahul Shelke", "Harish Choudhary", "S. S. Sambare"],
    year: "2019",
    venue: "IEEE ICCUBEA",
    type: "conference",
  },
  {
    id: "26",
    indexing: "Scopus",
    title: "Modified Efficient Handover Mechanism for WiFi-WiMAX Heterogeneous Network Environment",
    authors: ["S. S. Sambare", "Dr. M. U. Kharat", "Abhilasha Zatke"],
    year: "2018",
    venue: "IEEE Third International Conference on Computing, Communication, Control And Automation",
    type: "conference",
  },
  {
    id: "27",
    indexing: "Scopus",
    title: "Congestion Control in Heterogeneous Wireless Networks Based on 802.21 Standard",
    authors: ["Kunal Lale", "Santosh Sambare"],
    year: "2017",
    venue: "IEEE Third International Conference on Computing, Communication, Control And Automation",
    type: "conference",
  },
  {
    id: "28",
    indexing: "Scopus",
    title: "Diet Recommendation Based on Prakriti and Season Using Fuzzy Ontology",
    authors: ["Shital V. Chavan", "S. S. Sambare", "Dr. Anuruddha Joshi"],
    year: "2016",
    venue: "IEEE ICCUBEA",
    type: "conference",
  },
];